特別課題模写コーディング(方向性確認)
w-shaulabg/HTML-CSS pull request #13
Opened 2022-11-29 11:25 UTC by w-shaulabg

お疲れ様です！
模写コーディングの現在の状況をご報告いたします！
ご確認のほどよろしくお願いいたします！！

↓練習用ページ↓
https://code-step.com/demo/html/profile/

↓ブラウザ表示結果↓
![Uploading screencapture-localhost-8080-reproductionHtml-reproduction-php-2022-11-29-20_18_26.png…]()

2022-12-09 07:02 UTC, gotokouichi requested changes
見た目の部分について、参考サイトと同様に実装ができていて良い感じですね！！

次回以降はclass名については、flex1, flex2…..というより、

以下のような感じで、よく使われるワードなどを調べてもらいながら

より適切な名前にしていただけたらと思います！😊

- wrapper
- contents
- button
- title
- text
- site-title
- image

改めて、BEMを意識しながら進めていただくとより勉強になるかと思います！😊

[https://cloudsmith.co.jp/blog/frontend/2021/03/1742107.html](https://cloudsmith.co.jp/blog/frontend/2021/03/1742107.html)

こちら参考コードになります！
`<body>

	<header class="header">
		<h1 class="header__siteTile"></h1>
		<div class="header__contents">
			<nav class="header__navigation">
				<ul class="header__list">
					<li class="header__listItem">
						<a class="header__link"></a>
					</li>
					<li class="header__listItem">
						<a class="header__link"></a>
					</li>
				</ul>
			</nav>
		</div>
	</header>

	<main class="main">
		<div class="About">
			<h2 class="About__title">About</h2>
      <img class="About__image" src="img/mainvisual.jpg" alt="テキストテキストテキスト">
    </div>

		<div class="bicycle">
			<h2 class="bicycle__title">bicycle</h2>
      <p class="bicycle__text"></p>
    </div>
	</main>

</body>`

2022-12-19 11:38 UTC, KatsuyaTanaka95 commented on src/public/reproductionCSS/reproduction.css
> +}
こちら模写したコードを参考に入れていただいたんですね！！
疑問点をどんどん学んでいただいていていつも通りさすがですね ^ ^
こちらも直近ではどう使うかわからないとこですが、
なんとなくでも理解できてるだけで、いざ出てきた時に理解しやすそうですね！😊

2022-12-19 11:47 UTC, KatsuyaTanaka95 approved these changes
こちら素晴らしいです！！
mergeしちゃいましょう！🙆😊

コメントさせていただいた箇所は覚えていきましょう！！！

2022-12-19 11:47 UTC, KatsuyaTanaka95 commented on src/public/reproductionCSS/reproduction.css
> +}
ここ最高です！！😊

2022-12-19 11:47 UTC, KatsuyaTanaka95 commented on src/public/reproductionCSS/reproduction.css
> +}
横いっぱいに広がっている画像を使用する場合はこのように書くことも多いみたいです！！
widthとheightを指定してしまう方法です！

2022-12-19 11:47 UTC, KatsuyaTanaka95 commented on src/public/reproductionCSS/reproduction.css
> +}
模写コードの方でここはどのようにしているかもスニペットにしておくと良いと思います！！
imgタグの上にあるブロック要素(今回の場合はh1タグ)の100%までしか広がらないように指定してあります！

2022-12-26 11:54 UTC, merged